name: n3n-docker
on:
  push:
    branches:
      - main
env:
  APP_VERSION: 3.4.1
  APP_NAME: n3n-docker
jobs:
  manifest-images:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: chenweiwen
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Create and push manifest images
        env:
          HTTP_PROXY: ${{vars.CLASH_HTTP_PROXY}}
          HTTPS_PROXY: ${{vars.CLASH_HTTP_PROXY}}
        run: |
          docker manifest create chenweiwen/n3n-docker:latest chenweiwen/n3n-docker:3.4.1-arm64 chenweiwen/n3n-docker:3.4.1-amd64
          docker manifest create chenweiwen/n3n-docker:3.4.1 chenweiwen/n3n-docker:3.4.1-arm64 chenweiwen/n3n-docker:3.4.1-amd64
