name: n3n-docker
on:
  push:
    branches:
      - main
env:
  APP_VERSION: 3.4.1
  APP_NAME: n3n-docker
jobs:
  manifest-images:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: chenweiwen
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Create and push manifest imagess
        uses: noelware/docker-manifest-action@master
        env:
          HTTP_PROXY: ${{vars.CLASH_HTTP_PROXY}}
          HTTPS_PROXY: ${{vars.CLASH_HTTP_PROXY}}
        with:
          inputs: chenweiwen/${{env.APP_NAME}}:latest, chenweiwen/${{env.APP_NAME}}:${{env.APP_VERSION}}
          images: chenweiwen/${{env.APP_NAME}}:${{env.APP_VERSION}}-arm64, chenweiwen/${{env.APP_NAME}}:${{env.APP_VERSION}}-amd64
          push: true
