on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'Docker tag'
        required: true
        type: string
        default: latest
        
env:
  APP_NAME: n3n-docker
  DOCKER_TAG: ${{ inputs.dockerTag }}
  HTTP_PROXY: ${{vars.CLASH_HTTP_PROXY}}
  HTTPS_PROXY: ${{vars.CLASH_HTTP_PROXY}}
jobs:
  sync-docker-hub:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: chenweiwen
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Sync Docker Hub
        run: |
          docker buildx imagetools create \
            --tag chenweiwen/${{env.APP_NAME}}:${{env.DOCKER_TAG}} \
            ${{vars.REGISTRY_URL}}/qibao/${{env.APP_NAME}}:${{env.DOCKER_TAG}} 